const Productos = [
   
        {id:1 ,categoria:"Motherboard",nombreproducto:"Mother Asrock Z390 Phantom Gaming 4S Wi-Fi BULK Pack S1151",imagen:"./src/img/motherboard1.jpg",precio:55000},
        {id:2,categoria:"Motherboard",nombreproducto:"Mother Asrock A520M-HDV AM4",imagen:"./src/img/motherboard2.jpg",precio:60000},
        {id:3,categoria:"Motherboard",nombreproducto:"Mother ASUS PRIME A320M-K AM4",imagen:"./src/img/motherboard3.jpg",precio:65000},
        {id:4,categoria:"Motherboard",nombreproducto:"Mother Asrock B450M-HDV 4.0 AM4 HDMI M.2 ",imagen:"./src/img/motherboard4.jpg",precio:70000},
        {id:5,categoria:"Motherboard",nombreproducto:"Mother MSI H510M PLUS V3 - Solo 10th Gen",imagen:"./src/img/motherboard5.jpg",precio:45000},
        {id:6,categoria:"Procesador",nombreproducto:"Procesador Intel Celeron G4900 3.10GHz Socket 1151 OEM Coffe Lake",imagen:"./src/img/procesador1.jpg",precio:6000},
        {id:7,categoria:"Procesador",nombreproducto:"Procesador AMD Athlon 3000G 3.5GHz + Radeon Vega 3 AM4",imagen:"./src/img/procesador2.jpg",precio:7000},
        {id:8,categoria:"Procesador",nombreproducto:"Procesador AMD Athlon 3000G 3.5GHz + Radeon Vega 3 AM4",imagen:"./src/img/procesador3.jpg",precio:8000},
        {id:9,categoria:"Procesador",nombreproducto:"Procesador Intel Pentium Gold G5400 3.7GHz Socket 1151 OEM Sin Cooler Coffe Lake",imagen:"./src/img/procesador4.jpg",precio:9000},
        {id:10,categoria:"Procesador",nombreproducto:"Procesador AMD RYZEN 3 3200G 4.0GHz Turbo + Radeon Vega 8 AM4 Wraith Stealth Cooler",imagen:"./src/img/procesador5.jpg",precio:10000},
        {id:11,categoria:"Memoria ram",nombreproducto:"Memoria Team DDR4 8GB 3200MHz Elite Plus Red CL 22",imagen:"./src/img/memoria1.jpg",precio:11000},
        {id:12,categoria:"Memoria ram",nombreproducto:"Memoria Team DDR4 8GB 3200MHz T-Force Vulcan Z Grey CL16",imagen:"./src/img/memoria2.jpg",precio:12000},
        {id:13,categoria:"Memoria ram",nombreproducto:"Memoria Patriot Viper DDR4 8GB 3200MHz Steel CL16",imagen:"./src/img/memoria3.jpg",precio:13000},
        {id:14,categoria:"Memoria ram",nombreproducto:"Memoria Kingston DDR4 8GB 3200MHz Sodimm Tipo Notebook*",imagen:"./src/img/memoria4.jpg",precio:14000},
        {id:15,categoria:"Memoria ram",nombreproducto:"Memoria Corsair DDR4 8GB 3200Mhz Vengeance LPX Black CL16",imagen:"./src/img/memoria5.jpg",precio:15000},
        {id:17,categoria:"fuentes",nombreproducto:"Fuente Antec 550W 80 Plus Bronze CSK550",imagen:"./src/img/fuente2.jpg",precio:17000},
        {id:18,categoria:"fuentes",nombreproducto:"Fuente Aerocool Cylon 500W Full Range RGB 80 Plus Bronze",imagen:"./src/img/fuente3.jpg",precio:18000},
        {id:19,categoria:"fuentes",nombreproducto:"Fuente Cougar 600W 80 Plus Bronze ATLAS OEM",imagen:"./src/img/fuente4.jpg",precio:19000},
        {id:20,categoria:"fuentes",nombreproducto:"Fuente Antec 650W 80 Plus Bronze CSK650",imagen:"./src/img/fuente5.jpg",precio:20000},
        {id:21,categoria:"gabinete",nombreproducto:"Gabinete Kolink Inspire K3 RGB M-ATX Vidrio Templado",imagen:"./src/img/gabinete1.jpg",precio:21000},
        {id:22,categoria:"gabinete",nombreproducto:"Gabinete Kolink Inspire X1 Vidrio Templado 1x120mm ARGB",imagen:"./src/img/gabinete2.jpg",precio:22000},
        {id:23,categoria:"gabinete",nombreproducto:"Gabinete Kolink Inspire K20 Vidrio Templado 1x120mm ARGB",imagen:"./src/img/gabinete3.jpg",precio:23000},
        {id:24,categoria:"gabinete",nombreproducto:"Gabinete Antec NX200M White Vidrio Templado",imagen:"./src/img/gabinete4.jpg",precio:24000},
        {id:25,categoria:"gabinete",nombreproducto:"Gabinete Antec NX200M Vidrio Templado",imagen:"./src/img/gabinete5.jpg",precio:25000},
        {id:26,categoria:"Placa de video",nombreproducto:"Placa de video rx874",imagen:"./src/img/placa1.jpg",precio:26000},
        {id:27,categoria:"Placa de video",nombreproducto:"Placa de video rx875",imagen:"./src/img/placa2.jpg",precio:27000},
        {id:28,categoria:"Placa de video",nombreproducto:"Placa de video rx873",imagen:"./src/img/placa3.jpg",precio:28000},
        {id:29,categoria:"Placa de video",nombreproducto:"Placa de video rx872",imagen:"./src/img/placa4.jpg",precio:29000},
        {id:30,categoria:"Placa de video",nombreproducto:"Placa de video rx879",imagen:"./src/img/placa5.jpg",precio:30000},
        {id:31,categoria:"monitor",nombreproducto:"monitor105",imagen:"./src/img/monitor1.jpg",precio:31000},
        {id:32,categoria:"monitor",nombreproducto:"monitor 4fs",imagen:"./src/img/monitor2.jpg",precio:32000},
        {id:33,categoria:"monitor",nombreproducto:"monitor x12",imagen:"./src/img/monitor3.jpg",precio:33000},
        {id:34,categoria:"monitor",nombreproducto:"monitor x13",imagen:"./src/img/monitor4.jpg",precio:34000},
        {id:35,categoria:"monitor",nombreproducto:"monitor x14",imagen:"./src/img/monitor5.jpg",precio:35000}
    ];